### ISSUE TITLE
Only initial lambda version (1) works

### ISSUE THREAD

**Issue by jesseadams** [aws-samples/cloudfront-authorization-at-edge#13]
For some reason, if I update the lambdas after the initial deployment and the versions update to 2 (or higher) this solution fails with a very generic error suggesting that there is an issue with the lambda permissions or the lambda configuration. If I drop the entire stack, and deploy the same change at version 1 it seems to work fine. I am using `CreateCloudFrontDistribution=false`

**Comment by ottokruse** [comment]
Hi Jesse. I just updated the code and added a "Version" parameter to the CloudFormation (SAM) template. While developing you can use that to force a new (valid) deployment of Lambda@Edge code. This worked for me, can you check if it also works for your workflow?

You can just put any value in the "Version" parameter; every time you want to redeploy the same stack, use a new version. If CloudFormation detects the version to have another value than during the previous stack deployment, it will update the Lambda@Edge functions. This is a bit of a "trick" to help CloudFormation understand something's changed.

**Comment by jesseadams** [comment]
To be clear, the versioning was working previously. Each time I changed the HTTP headers, for instance, the lambdas would update and the outputs would show the new version. For some reason, however, after my consuming stack updated the CloudFront behaviors with the new versions the lambdas no longer run. I thought my change was bad, but after reverting it and deploying a new version it was still not working. If I make my changes, drop the stack, and redeploy my changes work fine. I am just trying to avoid having to drop my consuming stack, this stack, and redeploying both every time I need to tweak one of the lambdas. It should be rare, I just don't want it to bite me in the future

Does that make sense?

**Comment by ottokruse** [comment]
Not following your workflow entirely but I suspect your issue will be solved now by the change I mentioned. Can you maybe try deploying again?

```
sam deploy --template-file packaged.yaml \
           --stack-name your-stack-name  \
           --capabilities CAPABILITY_IAM \
           --parameter-overrides EmailAddress=you@example.com Version=$(date +%s) \
           --region us-east-1
```

Note the Version parameter. Which in this example is filled with a timestamp, which makes it different each time, thereby triggering the complete redeployment.

**Comment by ottokruse** [comment]
"For some reason, however, after my consuming stack updated the CloudFront behaviors with the new versions the lambdas no longer run."

Can you explain a bit more about the consuming stack? How are the stacks related?

**Comment by jesseadams** [comment]
So I had a pre-existing CFN stack that had CloudFront setup with a simple HTTP BasicAuth Lambda. I am migrating to this solution to see how it all works. 

I added this parameter to my stack:
```yaml
  AuthAtEdgeStackName:
    Type: String
    Description: The name of the AWS SAM stack that includes the lambdas and cognito setup for auth
    Default: cloudfront-authorization-at-edge
```
And here is a sample of how I am consuming the lambdas:
```yaml
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: true
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN:
                Fn::ImportValue:
                  !Sub "${AuthAtEdgeStackName}-CheckAuthHandler"
            - EventType: origin-response
              LambdaFunctionARN:
                Fn::ImportValue:
                  !Sub "${AuthAtEdgeStackName}-HttpHeadersHandler"
          TargetOriginId: s3Origin
          ViewerProtocolPolicy: redirect-to-https
```
I am deleting both stacks now and I will rebase your changes and let you know how it goes. If I run into further issues, I'll pass along more details on error messages, etc.
