### ISSUE TITLE
Question about Origins

### ISSUE THREAD

**Issue by picosam** [aws-samples/cloudfront-authorization-at-edge#23]
Thanks a lot for such a complete and useful work! When looking at the example of reusing auth with my own Cloudfront distribution, I see the following:

```
        Origins:
          - DomainName: example.org
            Id: dummy-origin
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
          - DomainName: example.com
            Id: protected-origin
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
```

Are we supposed to replace `example.org` and `example.com` there with other values? Also, are we supposed to add our own S3 Bucket where we'll be deploying our SPA?

Thanks again,
Sammy
