### ISSUE TITLE
[Feature Request] support settings certificate arn for cloudfront distribution

### ISSUE THREAD

**Issue by stevie-** [aws-samples/cloudfront-authorization-at-edge#304]
Support setting certificate arn for cloudfront distribution.

```yaml
Parameters:
  AcmCertificateArn:
    Type: String
    Description: The ARN of the ACM certificate to use for the CloudFront distribution
    Default: ""

      DistributionConfig:
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases: !Ref AlternateDomainNames
```
