### ISSUE TITLE
AcmCertificateArn

### ISSUE THREAD

**Issue by sebastien-rabby** [aws-samples/cloudfront-authorization-at-edge#307]
Hi,

I noticed that Acmcertificatearn is now valid to set in the template.yaml:   

```
AcmCertificateArn:
    Description: The ARN of an existing ACM certificate to use for the CloudFront distribution.
    Type: String
    Default: ""

```
But when i want to deploy the cloudformation stack with the option 1: 

> Option 1: Deploy through the Serverless Application Repository
> The solution can be deployed with a few clicks from the [Serverless Application Repository](https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge).

I don't see the parameter AcmCertificateArn and aliases either.

Is it normal ?
Thanks and regards
