### ISSUE TITLE
[Question] - use of "CookieSettings" for custom data

### ISSUE THREAD

**Issue by rpattcorner** [aws-samples/cloudfront-authorization-at-edge#71]
@ottokruse 
We're working on a well known problem of providing configuration data to an S3 SPA, while trying to keep the "cloudfront-authorization-at-edge" (CFAAE ) an intact authorization 'black box'.

The problem in a nutshell is that a SPA in S3 has no way to acquire configuration unless it's compiled in -- not even the name of the bucket it resides in.

One of our developers came up with a great idea -- since our CloudFormation that invokes the CFAAE knows everything we need to pass through to the SPA, we could insert the CFN data in a cookie using the "CookieSettings" parameter to the SAM application, like this example for a bucketname:

```
  LambdaEdgeProtection:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge
        SemanticVersion: !Ref SemanticVersion
      Parameters:
        CreateCloudFrontDistribution: "false"
        HttpHeaders: !Ref HttpHeaders
        AlternateDomainNames: !Join [ ",", !Ref AlternateDomainNames ]
        CookieSettings: "{\"bucketName\":\"hardcoded\", \"idToken\": null,\"accessToken\": null,\"refreshToken\": null,\"nonce\": null}"
```

That worked brilliantly in the sense that it dynamically altered the CookieSettings in each Lambda@Edge's `configuration.json`, for example:

```
  "cookieSettings": {
    "bucketName: "hardcoded",
    "idToken": null,
    "accessToken": null,
    "refreshToken": null,
    "nonce": null
  },
```
but it had no effect whatever on the app ... the `bucketName` cookie was never created or passed to the application, although all the others were.

Which makes me think I'd misunderstood the use of cookie settings ... perhaps they are a way to set behavioural metadata on already-defined cookies, and defining a new cookie would require modifying (all?) the lambdas to recognize and propagate the cookie end to end.  Which is a place we do not want to go, per the 'black box' constraint.

I tried one more time, and attempted to sneak a value into a predefined cookie, in this case the accessToken:

`CookieSettings: "{\"idToken\": null,\"accessToken\": \"bucketname\",\"refreshToken\": null,\"nonce\": null}"`

but the bucketname just gets replaced by the real access token, as one might expect.

Is there a way to pass custom values into cookies all the way through the framework to the SPA that I'm just not seeing?

If not, that would be a terrific feature, as almost every SPA has need of some data that is available in the installing cloudFormation script.  But I'm all on the application side right now ...

R.
